import keyMirror from 'keymirror';

export default keyMirror({
	CREATE_FLOWER: null,
	CREATE_FLOWER_SUCCESS: null,
	CREATE_FLOWER_ERROR: null,
	UPDATE_FLOWER: null,
	UPDATE_FLOWER_SUCCESS: null,
	UPDATE_FLOWER_ERROR: null,
	GET_FLOWER_BY_ID: null,
	GET_FLOWER_BY_ID_SUCCESS: null,
	GET_FLOWER_BY_ID_ERROR: null,
	GET_FLOWERS: null,
	GET_FLOWERS_SUCCESS: null,
	GET_FLOWERS_ERROR: null,
	GET_FLOWERS_FILTERED: null,
	GET_FLOWERS_FILTERED_SUCCESS: null,
	GET_FLOWERS_FILTERED_ERROR: null,
	MARK_FLOWER_FAVORITE: null,
	MARK_FLOWER_FAVORITE_SUCCESS: null,
	GET_FAVORITE_FLOWERS: null,
	GET_FAVORITE_FLOWERS_SUCCESS: null,
	GET_FAVORITE_FLOWERS_ERROR: null,
	RESET_FLOWERS: null
});