import keyMirror from 'keymirror';

export default keyMirror({
    LOG_IN_USER: null,
    LOG_IN_USER_SUCCESS: null,
	LOG_IN_USER_ERROR: null,
	LOG_OUT_USER: null,
	LOG_OUT_USER_SUCCESS: null,
	SIGN_UP_USER: null,
	SIGN_UP_USER_SUCCESS: null,
	SIGN_UP_USER_ERROR: null,
	GET_PROFILE: null,
	GET_PROFILE_SUCCESS: null,
	GET_PROFILE_BY_ID: null,
	GET_PROFILE_BY_ID_SUCCESS: null,
	GET_PROFILE_BY_ID_ERROR: null,
	CHECK_USER_LOGGED_IN: null,
	EDIT_PROFILE: null,
	EDIT_PROFILE_SUCCESS: null,
	EDIT_PROFILE_ERROR: null,
	DELETE_PROFILE: null,
	DELETE_PROFILE_SUCCESS: null,
	DELETE_PROFILE_ERROR: null
});
